const BAD_REQUEST = 400;
const AUTH_ERROR = 401;
const FORBIDDEN = 403;
const NOT_FOUND = 404;
const CONFLICT_ERROR = 409;
const INTERNAL_SERVER_ERROR = 500;
const STATUS_CREATED = 201;

module.exports = {
  BAD_REQUEST,
  AUTH_ERROR,
  FORBIDDEN,
  NOT_FOUND,
  CONFLICT_ERROR,
  INTERNAL_SERVER_ERROR,
  STATUS_CREATED,
};
